config/routes.rb
Rails.application.routes.draw do


devise_for :customers, controllers: {
  sessions: 'customers/sessions',
  registrations: 'customers/registrations'
}
devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}
  resources :order_details, only: [:update, :create]
  resources :items
  resources :cart_items do
   collection do
      delete 'destroy_all'
   end
  end

  get "/orders/thanks" => "orders#thanks", as: 'orders_thanks'
  resources :orders
  post "/orders/confirm" => "orders#confirm", as: 'orders_confirm'
  resources :addresses
  get "/customers/quit" => "customers#quit", as: 'customers_quit'
  patch "/customers/out" => "customers#out", as: 'customers_out'
  resources :customers, only: [:show, :edit, :update]
  root to: 'homes#top'
  get 'homes/about'



  namespace :admin do
    get 'customer/index'
    get 'customer/show'
    get 'customer/edit'
    get 'homes/top'
  end

  namespace :admin do
    resources :genres
    resources :items
    resources :customers
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  attachment :image
  has_many :cart_items, dependent: :destroy
  belongs_to :customer, optional: true
  has_many :order_details, dependent: :destroy
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
   @item = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.all
    @item = Item.new(item_params)
    @item.save!
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def edit
   @item = Item.find(params[:id])
  end


  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active )
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_customer!
  def index
    @item = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<h3>商品一覧（全<%= Item.count %>件）</h3>


  <% @item.each do |item| %>
    <%= link_to item_path(item) do %>
    <%= attachment_image_tag item, :image, :size => '100x100' %>
    <% end %></br>
    <%= item.name %></br>
    ￥  <%= (1.1*(item.price) ).round %></br></br>
  <% end %>

app/views/items/show.html.erb
  <%= attachment_image_tag @item, :image, :size => '200x200' %></br>
    <h3><%= @item.name %></h3>
    <%= @item.introduction %></br>
    </br>
    ￥ <%= (1.1*(@item.price) ).round %>(税込)

    <%= form_with model: @cart_item, url:cart_items_path, local:true do |f| %>
    <%= f.hidden_field :item_id, value: @item.id %>
    <%= f.hidden_field :customer_id, value: current_customer.id %>
    <%= f.select :amount, *[1..10] %>
    <%= f.submit "カートに入れる" %>
    <% end %>